server:
  port: 8001

app:
  receive:
    name: receive
    url: http://localhost:8002

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic